Intelligent-Navigation-System/fetch_api/urls.py
from django.conf.urls import url

from . import views
from .views import (
    GetNodesCount,
    GetNodesData,
    GetNodeData,
    GetCountries,
    GetJurisdictions,
    GetDataSource,
)


urlpatterns = [
    url(r'^count[/]?$', GetNodesCount.as_view(), name='get_nodes_count'),
    url(r'^nodes[/]?$', GetNodesData.as_view(), name='get_nodes_data'),
    url(r'^node[/]?$', GetNodeData.as_view(), name='get_node_data'),
    url(r'^countries[/]?$', GetCountries.as_view(), name='get_countries'),
    url(r'^jurisdictions[/]?$', GetJurisdictions.as_view(), name='get_jurisdictions'),
    url(r'^datasource[/]?$', GetDataSource.as_view(), name='get_data_source'),
    url(r'^search/', views.search, name='search'),
]

Intelligent-Navigation-System/mytest/urls.py
import xadmin
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url, include
from django.views.generic import TemplateView

urlpatterns = [
    url('admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name='index1.html'), name='index'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    # url('xadmin/', xadmin.site.urls),

    url(r'^fetch/', include(('fetch_api.urls','fetch'),namespace='fetch')),
#用户路由
    url(r'^user/', include(('userapp.urls', 'user'), namespace='user')),
]

Intelligent-Navigation-System/userapp/urls.py
from django.conf.urls import url

from userapp import views

urlpatterns = [
    url(r'^login', views.login_user, name='login_user'),
]

mytest/mytest/fetch_api/urls.py
from django.conf.urls import url

from .views import (
    GetNodesCount,
    GetNodesData,
    GetNodeData,
    GetCountries,
    GetJurisdictions,
    GetDataSource,
)


urlpatterns = [
    url(r'^count[/]?$', GetNodesCount.as_view(), name='get_nodes_count'),
    url(r'^nodes[/]?$', GetNodesData.as_view(), name='get_nodes_data'),
    url(r'^node[/]?$', GetNodeData.as_view(), name='get_node_data'),
    url(r'^countries[/]?$', GetCountries.as_view(), name='get_countries'),
    url(r'^jurisdictions[/]?$', GetJurisdictions.as_view(), name='get_jurisdictions'),
    url(r'^datasource[/]?$', GetDataSource.as_view(), name='get_data_source'),
]

mytest/mytest/mytest/urls.py
import xadmin
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url, include
from django.views.generic import TemplateView

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    # url('xadmin/', xadmin.site.urls),

    url(r'^fetch/', include('fetch_api.urls')),
#用户路由
    url(r'^user/', include(('userapp.urls', 'user'), namespace='user')),
]

mytest/mytest/adminapp/xadmin/forms.py
from django import forms

from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm

from django.utils.translation import ugettext_lazy, ugettext as _

from django.contrib.auth import get_user_model

ERROR_MESSAGE = ugettext_lazy("Please enter the correct username and password "
                              "for a staff account. Note that both fields are case-sensitive.")


class AdminAuthenticationForm(AuthenticationForm):
    """
    A custom authentication form used in the admin app.

    """
    this_is_the_login_form = forms.BooleanField(
        widget=forms.HiddenInput, initial=1,
        error_messages={'required': ugettext_lazy("Please log in again, because your session has expired.")})

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        message = ERROR_MESSAGE

        if username and password:
            self.user_cache = authenticate(
                username=username, password=password)
            if self.user_cache is None:
                if u'@' in username:
                    User = get_user_model()
                    # Mistakenly entered e-mail address instead of username? Look it up.
                    try:
                        user = User.objects.get(email=username)
                    except (User.DoesNotExist, User.MultipleObjectsReturned):
                        # Nothing to do here, moving along.
                        pass
                    else:
                        if user.check_password(password):
                            message = _("Your e-mail address is not your username."
                                        " Try '%s' instead.") % user.username
                raise forms.ValidationError(message)
            elif not self.user_cache.is_active or not self.user_cache.is_staff:
                raise forms.ValidationError(message)
        return self.cleaned_data

mytest/adminapp/xadmin/views/edit.py
from __future__ import absolute_import
import copy

from crispy_forms.utils import TEMPLATE_PACK
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied, FieldError
from django.db import models, transaction
from django.forms.models import modelform_factory, modelform_defines_fields
from django.http import Http404, HttpResponseRedirect
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.encoding import force_text
from django.utils.html import escape
from django.utils.text import capfirst, get_text_list
from django.template import loader
from django.utils.translation import ugettext as _
from django.forms.widgets import Media
from xadmin import widgets
from xadmin.layout import FormHelper, Layout, Fieldset, TabHolder, Container, Column, Col, Field
from xadmin.util import unquote
from xadmin.views.detail import DetailAdminUtil

from .base import ModelAdminView, filter_hook, csrf_protect_m


FORMFIELD_FOR_DBFIELD_DEFAULTS = {
    models.DateTimeField: {
        'form_class': forms.SplitDateTimeField,
        'widget': widgets.AdminSplitDateTime
    },
    models.DateField: {'widget': widgets.AdminDateWidget},
    models.TimeField: {'widget': widgets.AdminTimeWidget},
    models.TextField: {'widget': widgets.AdminTextareaWidget},
    models.URLField: {'widget': widgets.AdminURLFieldWidget},
    models.IntegerField: {'widget': widgets.AdminIntegerFieldWidget},
    models.BigIntegerField: {'widget': widgets.AdminIntegerFieldWidget},
    models.CharField: {'widget': widgets.AdminTextInputWidget},
    models.IPAddressField: {'widget': widgets.AdminTextInputWidget},
    models.ImageField: {'widget': widgets.AdminFileWidget},
    models.FileField: {'widget': widgets.AdminFileWidget},
    models.ForeignKey: {'widget': widgets.AdminSelectWidget},
    models.OneToOneField: {'widget': widgets.AdminSelectWidget},
    models.ManyToManyField: {'widget': widgets.AdminSelectMultiple},
}


class ReadOnlyField(Field):
    template = "xadmin/layout/field_value.html"

    def __init__(self, *args, **kwargs):
        self.detail = kwargs.pop('detail')
        super(ReadOnlyField, self).__init__(*args, **kwargs)

    def render(self, form, form_style, context, template_pack=TEMPLATE_PACK, **kwargs):
        html = ''
        for field in self.fields:
            result = self.detail.get_field_result(field)
            field = {'auto_id': field}
            html += loader.render_to_string(
                self.template, {'field': field, 'result': result})
        return html


class ModelFormAdminView(ModelAdminView):
    form = forms.ModelForm
    formfield_overrides = {}
    readonly_fields = ()
    style_fields = {}
    exclude = None
    relfield_style = None

    save_as = False
    save_on_top = False

    add_form_template = None
    change_form_template = None

    form_layout = None

    def __init__(self, request, *args, **kwargs):
        overrides = FORMFIELD_FOR_DBFIELD_DEFAULTS.copy()
        overrides.update(self.formfield_overrides)
        self.formfield_overrides = overrides
        super(ModelFormAdminView, self).__init__(request, *args, **kwargs)

    @filter_hook
    def formfield_for_dbfield(self, db_field, **kwargs):
        # If it uses an intermediary model that isn't auto created, don't show
        # a field in admin.
        if isinstance(db_field, models.ManyToManyField) and not db_field.remote_field.through._meta.auto_created:
            return None

        attrs = self.get_field_attrs(db_field, **kwargs)
        return db_field.formfield(**dict(attrs, **kwargs))

    @filter_hook
    def get_field_style(self, db_field, style, **kwargs):
        if style in ('radio', 'radio-inline') and (db_field.choices or isinstance(db_field, models.ForeignKey)):
            attrs = {'widget': widgets.AdminRadioSelect(
                attrs={'inline': 'inline' if style == 'radio-inline' else ''})}
            if db_field.choices:
                attrs['choices'] = db_field.get_choices(
                    include_blank=db_field.blank,
                    blank_choice=[('', _('Null'))]
                )
            return attrs

        if style in ('checkbox', 'checkbox-inline') and isinstance(db_field, models.ManyToManyField):
            return {'widget': widgets.AdminCheckboxSelect(attrs={'inline': style == 'checkbox-inline'}),
                    'help_text': None}

    @filter_hook
    def get_field_attrs(self, db_field, **kwargs):

        if db_field.name in self.style_fields:
            attrs = self.get_field_style(
                db_field, self.style_fields[db_field.name], **kwargs)
            if attrs:
                return attrs

        if hasattr(db_field, "rel") and db_field.rel:
            related_modeladmin = self.admin_site._registry.get(db_field.rel.to)
            if related_modeladmin and hasattr(related_modeladmin, 'relfield_style'):
                attrs = self.get_field_style(
                    db_field, related_modeladmin.relfield_style, **kwargs)
                if attrs:
                    return attrs

        if db_field.choices:
            return {'widget': widgets.AdminSelectWidget}

        for klass in db_field.__class__.mro():
            if klass in self.formfield_overrides:
                return self.formfield_overrides[klass].copy()

        return {}

    @filter_hook
    def prepare_form(self):
        self.model_form = self.get_model_form()

    @filter_hook
    def instance_forms(self):
        self.form_obj = self.model_form(**self.get_form_datas())

    def setup_forms(self):
        helper = self.get_form_helper()
        if helper:
            self.form_obj.helper = helper

    @filter_hook
    def valid_forms(self):
        return self.form_obj.is_valid()

    @filter_hook
    def get_model_form(self, **kwargs):
        """
        Returns a Form class for use in the admin add view. This is used by
        add_view and change_view.
        """
        if self.exclude is None:
            exclude = []
        else:
            exclude = list(self.exclude)
        exclude.extend(self.get_readonly_fields())
        if self.exclude is None and hasattr(self.form, '_meta') and self.form._meta.exclude:
            # Take the custom ModelForm's Meta.exclude into account only if the
            # ModelAdmin doesn't define its own.
            exclude.extend(self.form._meta.exclude)
        # if exclude is an empty list we pass None to be consistant with the
        # default on modelform_factory
        exclude = exclude or None
        defaults = {
            "form": self.form,
            "fields": self.fields and list(self.fields) or None,
            "exclude": exclude,
            "formfield_callback": self.formfield_for_dbfield,
        }
        defaults.update(kwargs)

        if defaults['fields'] is None and not modelform_defines_fields(defaults['form']):
            defaults['fields'] = forms.ALL_FIELDS

        return modelform_factory(self.model, **defaults)

        try:
            return modelform_factory(self.model, **defaults)
        except FieldError as e:
            raise FieldError('%s. Check fields/fieldsets/exclude attributes of class %s.'
                             % (e, self.__class__.__name__))

    @filter_hook
    def get_form_layout(self):
        layout = copy.deepcopy(self.form_layout)
        arr = self.form_obj.fields.keys()
        if six.PY3:
            arr = [k for k in arr]
        fields = arr + list(self.get_readonly_fields())

        if layout is None:
            layout = Layout(Container(Col('full',
                                          Fieldset("", *fields, css_class="unsort no_title"), horizontal=True, span=12)
                                      ))
        elif type(layout) in (list, tuple) and len(layout) > 0:
            if isinstance(layout[0], Column):
                fs = layout
            elif isinstance(layout[0], (Fieldset, TabHolder)):
                fs = (Col('full', *layout, horizontal=True, span=12),)
            else:
                fs = (Col('full', Fieldset("", *layout, css_class="unsort no_title"), horizontal=True, span=12),)

            layout = Layout(Container(*fs))

            rendered_fields = [i[1] for i in layout.get_field_names()]
            container = layout[0].fields
            other_fieldset = Fieldset(_(u'Other Fields'), *[f for f in fields if f not in rendered_fields])

            if len(other_fieldset.fields):
                if len(container) and isinstance(container[0], Column):
                    container[0].fields.append(other_fieldset)
                else:
                    container.append(other_fieldset)

        return layout

    def get_form_helper(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.include_media = False
        helper.add_layout(self.get_form_layout())

        # deal with readonly fields
        readonly_fields = self.get_readonly_fields()
        if readonly_fields:
            detail = self.get_model_view(
                DetailAdminUtil, self.model, self.form_obj.instance)
            for field in readonly_fields:
                helper[field].wrap(ReadOnlyField, detail=detail)

        return helper

    @filter_hook
    def get_readonly_fields(self):
        """
        Hook for specifying custom readonly fields.
        """
        return self.readonly_fields

    @filter_hook
    def save_forms(self):
        self.new_obj = self.form_obj.save(commit=False)

    @filter_hook
    def change_message(self):
        change_message = []
        if self.org_obj is None:
            change_message.append(_('Added.'))
        elif self.form_obj.changed_data:
            change_message.append(_('Changed %s.') % get_text_list(self.form_obj.changed_data, _('and')))

        change_message = ' '.join(change_message)
        return change_message or _('No fields changed.')

    @filter_hook

mytest/adminapp/xadmin/views/website.py
from __future__ import absolute_import
from django.utils.translation import ugettext as _
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.views.decorators.cache import never_cache
from django.contrib.auth.views import LoginView as login
from django.contrib.auth.views import LogoutView as logout
from django.http import HttpResponse

from .base import BaseAdminView, filter_hook
from .dashboard import Dashboard
from xadmin.forms import AdminAuthenticationForm
from xadmin.models import UserSettings
from xadmin.layout import FormHelper


class IndexView(Dashboard):
    title = _("Main Dashboard")
    icon = "fa fa-dashboard"

    def get_page_id(self):
        return 'home'


class UserSettingView(BaseAdminView):

    @never_cache
    def post(self, request):
        key = request.POST['key']
        val = request.POST['value']
        us, created = UserSettings.objects.get_or_create(
            user=self.user, key=key)
        us.value = val
        us.save()
        return HttpResponse('')


class LoginView(BaseAdminView):

    title = _("Please Login")
    login_form = None
    login_template = None

    @filter_hook
    def update_params(self, defaults):
        pass

    @never_cache
    def get(self, request, *args, **kwargs):
        context = self.get_context()
        helper = FormHelper()
        helper.form_tag = False
        helper.include_media = False
        context.update({
            'title': self.title,
            'helper': helper,
            'app_path': request.get_full_path(),
            REDIRECT_FIELD_NAME: request.get_full_path(),
        })
        defaults = {
            'extra_context': context,
            # 'current_app': self.admin_site.name,
            'authentication_form': self.login_form or AdminAuthenticationForm,
            'template_name': self.login_template or 'xadmin/views/login1.html',
        }
        self.update_params(defaults)
        # return login(request, **defaults)
        return login.as_view(**defaults)(request)

    @never_cache
    def post(self, request, *args, **kwargs):
        return self.get(request)


class LogoutView(BaseAdminView):

    logout_template = None
    need_site_permission = False

    @filter_hook
    def update_params(self, defaults):
        pass

    @never_cache
    def get(self, request, *args, **kwargs):
        context = self.get_context()
        defaults = {
            'extra_context': context,
            # 'current_app': self.admin_site.name,
            'template_name': self.logout_template or 'xadmin/views/logged_out.html',
        }
        if self.logout_template is not None:
            defaults['template_name'] = self.logout_template

        self.update_params(defaults)
        # return logout(request, **defaults)
        return logout.as_view(**defaults)(request)

    @never_cache
    def post(self, request, *args, **kwargs):
        return self.get(request)

mytest/templates/login1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>智能导航系统</title>
    <link href="{% url 'user:login_user' %}" type="text/css" rel="stylesheet">
</head>
<body>
<form action="#" method="post" name="message">
    {% csrf_token %}
    <label for="username">手机号</label><br>
    <input type="text" name="username" id="username">
    <br>
    <label for="password">密码</label><br>
    <input type="text" name="password" id="password">
    <br>
    <button type="submit">提交</button>
</form>
</body>
</html>

mytest/templates/pathsearch.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>添加点标记</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
<!--  <style>-->
<!--    body{font-size:14px;}-->
<!--    html,-->
<!--    #container {-->
<!--      overflow: hidden;-->
<!--      width: 90%;-->
<!--      height: 90%;-->
<!--      margin: 0;-->
<!--      font-family: "微软雅黑";-->
<!--    }-->

  </style>

  <style type="text/css">
    body, html,#allmap {width: 100%;height: 100%;overflow: hidden;margin:0;font-family:"微软雅黑";}
  </style>

  <script type="text/javascript" src="//api.map.baidu.com/api?type=webgl&v=1.0&ak=K3wK3NQLZMExb9VLnPXhsH1oEC47uCcL"></script>
  <script type="text/javascript" src="//api.map.baidu.com/api?type=subway&v=1.0&ak=K3wK3NQLZMExb9VLnPXhsH1oEC47uCcL"></script>
  <link rel="stylesheet" href="{% static 'css/pathsearch.css' %}">

</head>
<body>
<!--<input type="text">-->
<!--  <div id="container"></div>-->
<div>
    <form action="{% url 'fetch:search' %}" method="post" name="message">
    {% csrf_token %}
    <label for="start">起点</label><br>
    <input type="text" name="startname" id="start">
    <br>
    <label for="end">终点</label><br>
    <input type="text" name="endname" id="end">
    <br>
    <button type="submit">提交</button>
    </form>
{#  <div class="searchbox">#}
{#    起点：<input class="txt" type="text" id="startInput"/>#}
{#    终点：<input class="txt" type="text" id="endInput"/>#}
{#    <input type="button" value="导航" onclick="mDriving()"/>#}
{##}
{#  </div>#}
</div>
<div>{{ paths }}</div>
<div>{{ start }}</div>
<div>{{ end }}</div>
<div class="clear"></div>
<div class="mainbox">
<!--  <div class="boxmap" id="containe"></div>-->
  <div class="boxmap" id="container"></div>
  <div class="boxmap" id="container1"></div>
  <div class="boxpanel hidden" id="box">
    <h5>起点选择 <a href="#" onclick="document.getElementById('startPanel').style.display='block';">(展开)</a></h5>
    <div id="startPanel"></div>
    <h5>终点选择 <a href="#" onclick="document.getElementById('endPanel').style.display='block';">(展开)</a></h5>
    <div id="endPanel"></div>
    <h5>导航</h5>
    <div id="drivingPanel"></div>
  </div>
</div>



</body>
</html>
<script type="text/javascript">

  var map = new BMapGL.Map('containe', {
    enableDblclickZoom: false,
    displayOptions: {
      building: false
    }
  });
  map.centerAndZoom('昆明市', 11);
  map.enableScrollWheelZoom(true);


  var bd = new BMapGL.Boundary();
  bd.get('昆明市', function (rs) {
    console.log('外轮廓：', rs.boundaries[0]);
    console.log('内镂空：', rs.boundaries[1]);
    var hole = new BMapGL.Polygon(rs.boundaries);
    map.addOverlay(hole);
    var ply = new BMapGL.Polygon(rs.boundaries[0])
    map.setViewport(ply.getPath());
  });

  var top_left_control = new BMapGL.ScaleControl({anchor: BMAP_ANCHOR_TOP_LEFT});// 左上角，添加比例尺
  map.addControl(top_left_control);//添加比例尺

  //单击获取点击的经纬度
  // map.addEventListener("click",function(e){
  //   $("#s-point").text(e.point.lng+","+e.point.lat);
  //   var marker = new BMap.Marker(e.point);
  //   map.addOverlay(marker);
  // });




</script>
<script type="text/javascript">
  /**
   * 从所有城市列表中获取北京信息
   * 结果格式
   * {
   *     keyword: 'beijing',
   *     name: '北京',
   *     citycode: '131'
   * }
   */
  /* globals BMapSub */
  var start='{{ start }}';
  var end='{{ end }}';
  var subwayCityName = '昆明';
  var list = BMapSub.SubwayCitiesList;
  var subwaycity = null;
  for (var i = 0; i < list.length; i++) {
    if (list[i].name === subwayCityName) {
      subwaycity = list[i];
      break;
    }
  }
  // 获取北京地铁数据-初始化地铁图
  var subway = new BMapSub.Subway('container1', subwaycity.citycode);
  var zoomControl  = new BMapSub.ZoomControl({
    anchor: BMAPSUB_ANCHOR_BOTTOM_RIGHT,
    offset: new BMapSub.Size(10,100)
  });
  subway.addControl(zoomControl);
  subway.addEventListener('subwayloaded', function() {
    var drct = new BMapSub.Direction(subway);
    drct.search(start, end);
    {#drct.search('昆明火车站', '苏家塘');#}
  });
  subway.addEventListener('directioncomplete', function() {
    alert('可以自定义点击详情后的操作！');
  });
</script>
<script type="text/javascript">
  var map = new BMapGL.Map('container', {
    enableDblclickZoom: false,
    displayOptions: {
      building: false
    }
  });
  map.centerAndZoom('昆明市', 11);
  map.enableScrollWheelZoom(true);

  var startInfowin =new BMapGL.InfoWindow("<p class='t-c'><input value='选为起点' type='button' onclick='startDeter();' /></p>");
  var endInfowin =new BMapGL.InfoWindow("<p class='t-c'><input value='选为终点' type='button' onclick='endDeter();' /></p>");

  var startResults =null;
  var endResults =null;

  var startPoint;
  var endPoint;

  //var driving = new BMap.DrivingRoute(map, {renderOptions:{map: map, autoViewport: true,panel:drivingPanel}});
  var driving = new BMapGL.DrivingRoute(map, {renderOptions:{map: map, autoViewport: true, panel:'drivingPanel'}});



  var startOption = {
    onSearchComplete: function(results){
      // 判断状态是否正确
      if (startSearch.getStatus() == BMAP_STATUS_SUCCESS){
        startResults = results;
        var s = [];
        for (var i =0; i < results.getCurrentNumPois(); i ++){
          s.push("<div><p><a onmouseover='map.openInfoWindow(startInfowin,startResults.getPoi("+ i +").point);' href='#'>");
          s.push(results.getPoi(i).title);
          s.push("</a></p><p>");
          s.push(results.getPoi(i).address);
          s.push("</p></div>");
        }
        document.getElementById("startPanel").innerHTML = s.join("");
      }else{startResults =null;}
    }
  };
  var endOption = {
    onSearchComplete: function(results){
      // 判断状态是否正确
      if (endSearch.getStatus() == BMAP_STATUS_SUCCESS){
        endResults = results;
        var s = [];
        for (var i =0; i < results.getCurrentNumPois(); i ++){
          s.push("<div><p><a href='#' onmouseover='map.openInfoWindow(endInfowin,endResults.getPoi("+ i +").point);'>");
          s.push(results.getPoi(i).title);
          s.push("</a></p><p>");
          s.push(results.getPoi(i).address);
          s.push("</p></div>");
        }
        document.getElementById("endPanel").innerHTML = s.join("");
      }else{endResults =null;}
    }
  };
  //创建2个搜索实例
  var startSearch =new BMapGL.LocalSearch(map,startOption);
  var endSearch =new BMapGL.LocalSearch(map,endOption);
  // var walking = new BMapGL.WalkingRoute(map, {renderOptions: {map: map, panel: "r-result", autoViewport: true}});
  // walking.search("西单", "慈云寺");

  function mDriving(){
    var startPlace = document.getElementById("startInput").value;
    var endPlace = document.getElementById("endInput").value;
    startSearch.search(startPlace);
    endSearch.search(endPlace);
    document.getElementById("box").style.display="block";
  }

  function startDeter(){
    map.clearOverlays();
    startPoint = startInfowin.getPosition();
    var marker =new BMapGL.Marker(startPoint);
    map.addOverlay(marker);
    document.getElementById("startPanel").style.display="none";
  }
  function endDeter(){
    if(startPoint==null){alert("请先选择起点！");}
    else{
      endPoint = endInfowin.getPosition();
      driving.search(startPoint,endPoint);
      document.getElementById("endPanel").style.display="none";
    }
  }
</script>

mytest/templates/pathsearch0.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" class="full">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>线路规划</title>
    <script type="text/javascript" src="//api.map.baidu.com/api?type=subway&v=1.0&ak=K3wK3NQLZMExb9VLnPXhsH1oEC47uCcL"></script>
    <style type="text/css">
        #container{height:100%}
    </style>
</head>
<body>

<div>地铁站点路径搜索</div>
<div class="searchbox">
    <form action="" method="post" name="message">
    {% csrf_token %}
    <label for="start">起点</label><br>
    <input type="text" name="startname" id="start">
    <br>
    <label for="end">终点</label><br>
    <input type="text" name="endname" id="end">
    <br>
    <button type="submit">提交</button>
    </form>
</div>
<div>{{ paths }}</div>
<div>{{ start }}</div>
<div>{{ end }}</div>
<div id="container"></div>
<script type="text/javascript">
    /**
     * 从所有城市列表中获取北京信息
     * 结果格式
     * {
     *     keyword: 'beijing',
     *     name: '北京',
     *     citycode: '131'
     * }
     */
    /* globals BMapSub */
    var start='{{ start }}';
    var end='{{ end }}';
    var subwayCityName = '昆明';
    var list = BMapSub.SubwayCitiesList;
    var subwaycity = null;
    for (var i = 0; i < list.length; i++) {
        if (list[i].name === subwayCityName) {
            subwaycity = list[i];
            break;
        }
    }
    // 获取北京地铁数据-初始化地铁图
    var subway = new BMapSub.Subway('container', subwaycity.citycode);
    var zoomControl  = new BMapSub.ZoomControl({
        anchor: BMAPSUB_ANCHOR_BOTTOM_RIGHT,
        offset: new BMapSub.Size(10,100)
    });
    subway.addControl(zoomControl);
    subway.addEventListener('subwayloaded', function() {
        var drct = new BMapSub.Direction(subway);
        drct.search(start, end);
        {#drct.search('穿心鼓楼','昆明南火车站');#}
    });
    subway.addEventListener('directioncomplete', function() {
        alert('可以自定义点击详情后的操作！');
    });
</script>
</body>
</html>